using Microsoft.EntityFrameworkCore;
using BaseCore.Entities;
using BaseCore.Repository.EFCore;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace BaseCore.Services
{
    public class ProductService : IProductService
    {
        private readonly IProductRepositoryEF _productRepository;
        private readonly IRepository<Category> _categoryRepository;

        public ProductService(IProductRepositoryEF productRepository, IRepository<Category> categoryRepository)
        {
            _productRepository = productRepository;
            _categoryRepository = categoryRepository;
        }

        public async Task<List<Product>> GetAllProductsAsync()
        {
            var products = await _productRepository.GetAllAsync();
            return products.ToList();
        }

        public async Task<Product?> GetProductByIdAsync(int id)
        {
            var product = await _productRepository.GetByIdAsync(id);

            if (product != null)
            {
                var category = await _categoryRepository.GetByIdAsync(product.CategoryId);
                if (category != null)
                {
                    product.Category = category;
                }
            }

            return product;
        }

        public async Task<Product> CreateProductAsync(Product product)
        {
            // ID will be auto-generated by EF Core
            await _productRepository.AddAsync(product);
            return product;
        }

        public async Task UpdateProductAsync(Product product)
        {
            await _productRepository.UpdateAsync(product);
        }

        public async Task DeleteProductAsync(int id)
        {
            var product = await _productRepository.GetByIdAsync(id);
            if (product != null)
            {
                await _productRepository.DeleteAsync(product);
            }
        }

        public async Task<(List<Product> Products, int TotalCount)> SearchProductsAsync(string? keyword, int? categoryId, string? priceRange, string? size, int page, int pageSize, string sortType)
        {
            return await _productRepository.SearchAsync(keyword, categoryId, priceRange, size, page, pageSize, sortType);
        }
    }
}
